[build-system]
requires = ["setuptools", "wheel",  "cmake!=3.17.1,!=3.17.0", "pybind11~=2.6.1"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 100
target-version = ['py38', 'py39', 'py310', 'py311']
