# This code is part of Qiskit.
#
# (C) Copyright IBM 2021, 2022.
#
# This code is licensed under the Apache License, Version 2.0. You may
# obtain a copy of this license in the LICENSE.txt file in the root directory
# of this source tree or at http://www.apache.org/licenses/LICENSE-2.0.
#
# Any modifications or derivative works of this code must retain this
# copyright notice, and modified files need to carry a notice indicating
# that they have been altered from the originals.

name: Deploy Docs

on:
  push:
    branches:
      - main

jobs:
  docs_publish:
      name: Build and publish
      concurrency: ci-${{ github.ref }}
      runs-on: ubuntu-latest
      if: github.repository_owner == 'qiskit-community'
      steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: Set up Python 3.9
          uses: actions/setup-python@v4
          with:
            python-version: '3.9'
        - name: Install Non-Python Dependencies
          run: sudo apt-get install -y pandoc graphviz
        - name: Install tox
          run: python -m pip install -U tox
        - name: Build Docs Guide
          run: tox -e docs
        - name: Bypass Jekyll Processing # Necessary for setting the correct css path
          run: touch docs/_build/html/.nojekyll
        - name: Deploy
          uses: JamesIves/github-pages-deploy-action@v4
          with:
            folder: docs/_build/html
